apiVersion: v1
kind: Pod
metadata:
  name: pose-detectio
spec:
  nodeSelector:
    kubernetes.io/hostname : workergpu
  containers:
  - name: pose
    image: kd123456525/pose:latest
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      privileged: true
    volumeMounts:
    - name: video
      mountPath: /dev/video0
  volumes:
  - name: video
    hostPath:
      path: /dev/video0
