apiVersion: v1
kind: Pod
metadata:
  name: object-workergpu2-30501
  labels:
    app: object
spec:
  containers:
  - name: object
    image: harbor.pdc.tw/arha/object:latest
    readinessProbe:
      httpGet:
        path: /ping
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 7000
      hostPort: 30501
    resources:
      limits:
        nvidia.com/gpu: 1