# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gesture.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'gesture.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgesture.proto\"#\n\x12RecognitionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"J\n\x10RecognitionReply\x12\x13\n\x0b\x66rame_index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t2M\n\x12GestureRecognition\x12\x37\n\x0bRecognition\x12\x13.RecognitionRequest\x1a\x11.RecognitionReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gesture_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOGNITIONREQUEST']._serialized_start=17
  _globals['_RECOGNITIONREQUEST']._serialized_end=52
  _globals['_RECOGNITIONREPLY']._serialized_start=54
  _globals['_RECOGNITIONREPLY']._serialized_end=128
  _globals['_GESTURERECOGNITION']._serialized_start=130
  _globals['_GESTURERECOGNITION']._serialized_end=207
# @@protoc_insertion_point(module_scope)
