route:
  group_by: ['alertname', 'pod']
  receiver: webhook
  group_wait: 0s
  group_interval: 5m
  repeat_interval: 3h
receivers:
- name: webhook
  webhook_configs:
  - url: http://10.52.52.125:8080/alert