apiVersion: v1
kind: Pod
metadata:
  name: gesture-workergpu-30501
  labels:
    app: gesture
spec:
  nodeSelector:
    kubernetes.io/hostname : workergpu
  containers:
  - name: gesture
    image: harbor.pdc.tw/arha/gesture:latest
    ports:
    - containerPort: 50051
      hostPort: 30501
    resources:
      limits:
        nvidia.com/gpu: 1