apiVersion: v1
kind: Pod
metadata:
  name: object-workergpu2-30502
  labels:
    app: object
spec:
  nodeSelector:
    kubernetes.io/hostname : workergpu2
  containers:
  - name: object
    image: harbor.pdc.tw/arha/object:latest
    ports:
    - containerPort: 7000
      hostPort: 30502
    resources:
      limits:
        nvidia.com/gpu: 1